name: Common Flutter CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [hlokomela]
    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.3

      - run: flutter format --output none --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test
