name: hlokomela CD
on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.3

      - run: flutter build appbundle
        working-directory: hlokomela
      - uses: actions/upload-artifact@v2
        with:
          name: hlokomela.aab
          path: hlokomela/build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.3

      - run: flutter build ios --no-codesign
        working-directory: hlokomela
      - run: |
          cp -R hlokomela/build/ios/iphoneos Payload
          zip -ry0 hlokomela.ipa Payload
      - uses: actions/upload-artifact@v2
        with:
          name: hlokomela.ipa
          path: hlokomela.ipa

  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.3

      - run: flutter build web --base-href /hlokomela/
        working-directory: hlokomela
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hlokomela/build/web
          force_orphan: true
